/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SensorService } from "../sensor.service";
import { SensorCreateInput } from "./SensorCreateInput";
import { Sensor } from "./Sensor";
import { SensorFindManyArgs } from "./SensorFindManyArgs";
import { SensorWhereUniqueInput } from "./SensorWhereUniqueInput";
import { SensorUpdateInput } from "./SensorUpdateInput";
import { GasLeakAlertFindManyArgs } from "../../gasLeakAlert/base/GasLeakAlertFindManyArgs";
import { GasLeakAlert } from "../../gasLeakAlert/base/GasLeakAlert";
import { GasLeakAlertWhereUniqueInput } from "../../gasLeakAlert/base/GasLeakAlertWhereUniqueInput";
import { MaintenanceLogFindManyArgs } from "../../maintenanceLog/base/MaintenanceLogFindManyArgs";
import { MaintenanceLog } from "../../maintenanceLog/base/MaintenanceLog";
import { MaintenanceLogWhereUniqueInput } from "../../maintenanceLog/base/MaintenanceLogWhereUniqueInput";

export class SensorControllerBase {
  constructor(protected readonly service: SensorService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Sensor })
  async createSensor(@common.Body() data: SensorCreateInput): Promise<Sensor> {
    return await this.service.createSensor({
      data: {
        ...data,

        location: data.location
          ? {
              connect: data.location,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        location: {
          select: {
            id: true,
          },
        },

        serialNumber: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Sensor] })
  @ApiNestedQuery(SensorFindManyArgs)
  async sensors(@common.Req() request: Request): Promise<Sensor[]> {
    const args = plainToClass(SensorFindManyArgs, request.query);
    return this.service.sensors({
      ...args,
      select: {
        createdAt: true,
        id: true,

        location: {
          select: {
            id: true,
          },
        },

        serialNumber: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Sensor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async sensor(
    @common.Param() params: SensorWhereUniqueInput
  ): Promise<Sensor | null> {
    const result = await this.service.sensor({
      where: params,
      select: {
        createdAt: true,
        id: true,

        location: {
          select: {
            id: true,
          },
        },

        serialNumber: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Sensor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSensor(
    @common.Param() params: SensorWhereUniqueInput,
    @common.Body() data: SensorUpdateInput
  ): Promise<Sensor | null> {
    try {
      return await this.service.updateSensor({
        where: params,
        data: {
          ...data,

          location: data.location
            ? {
                connect: data.location,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          location: {
            select: {
              id: true,
            },
          },

          serialNumber: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Sensor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSensor(
    @common.Param() params: SensorWhereUniqueInput
  ): Promise<Sensor | null> {
    try {
      return await this.service.deleteSensor({
        where: params,
        select: {
          createdAt: true,
          id: true,

          location: {
            select: {
              id: true,
            },
          },

          serialNumber: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/gasLeakAlerts")
  @ApiNestedQuery(GasLeakAlertFindManyArgs)
  async findGasLeakAlerts(
    @common.Req() request: Request,
    @common.Param() params: SensorWhereUniqueInput
  ): Promise<GasLeakAlert[]> {
    const query = plainToClass(GasLeakAlertFindManyArgs, request.query);
    const results = await this.service.findGasLeakAlerts(params.id, {
      ...query,
      select: {
        alertLevel: true,
        alertTime: true,
        createdAt: true,
        id: true,

        sensor: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/gasLeakAlerts")
  async connectGasLeakAlerts(
    @common.Param() params: SensorWhereUniqueInput,
    @common.Body() body: GasLeakAlertWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      gasLeakAlerts: {
        connect: body,
      },
    };
    await this.service.updateSensor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/gasLeakAlerts")
  async updateGasLeakAlerts(
    @common.Param() params: SensorWhereUniqueInput,
    @common.Body() body: GasLeakAlertWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      gasLeakAlerts: {
        set: body,
      },
    };
    await this.service.updateSensor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/gasLeakAlerts")
  async disconnectGasLeakAlerts(
    @common.Param() params: SensorWhereUniqueInput,
    @common.Body() body: GasLeakAlertWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      gasLeakAlerts: {
        disconnect: body,
      },
    };
    await this.service.updateSensor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/maintenanceLogs")
  @ApiNestedQuery(MaintenanceLogFindManyArgs)
  async findMaintenanceLogs(
    @common.Req() request: Request,
    @common.Param() params: SensorWhereUniqueInput
  ): Promise<MaintenanceLog[]> {
    const query = plainToClass(MaintenanceLogFindManyArgs, request.query);
    const results = await this.service.findMaintenanceLogs(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        maintenanceDate: true,

        sensor: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/maintenanceLogs")
  async connectMaintenanceLogs(
    @common.Param() params: SensorWhereUniqueInput,
    @common.Body() body: MaintenanceLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      maintenanceLogs: {
        connect: body,
      },
    };
    await this.service.updateSensor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/maintenanceLogs")
  async updateMaintenanceLogs(
    @common.Param() params: SensorWhereUniqueInput,
    @common.Body() body: MaintenanceLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      maintenanceLogs: {
        set: body,
      },
    };
    await this.service.updateSensor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/maintenanceLogs")
  async disconnectMaintenanceLogs(
    @common.Param() params: SensorWhereUniqueInput,
    @common.Body() body: MaintenanceLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      maintenanceLogs: {
        disconnect: body,
      },
    };
    await this.service.updateSensor({
      where: params,
      data,
      select: { id: true },
    });
  }
}
